WIP: add conv operator
AdvancedClimateSystems/gonnx pull request #177
Opened 2023-10-16 09:07 UTC by Swopper050

Still in progress

2023-11-13 13:38 UTC, wipsel requested changes

2023-11-13 13:48 UTC, Swopper050 commented on ops/opset13/conv.go
> +	// Padding for the beginning and ending of each dimension. Cannot be used with autopad setting.
I left them out, as they are specified in the ONNX specs.

2023-11-13 13:48 UTC, Swopper050 commented on ops/opset13/conv.go
> +	c.kernelShape = kernel.Shape()[2:]
Yes it has at least 3 dimensions by ONNX definition.

2023-11-23 10:04 UTC, wipsel commented on ops/opset13/conv.go
> +			// nolint
But why?

2023-11-23 10:06 UTC, wipsel submitted a review, later dismissed
Approve but pl0x to fix last comment

2023-11-24 09:49 UTC, merged