Fix all lint (https://github.com/AdvancedClimateSystems/gonnx/issues/1)
AdvancedClimateSystems/gonnx pull request #178
Opened 2023-11-07 08:21 UTC by wipsel

2023-11-07 09:53 UTC, Swopper050 commented on ops/convert.go
> +
Deze nog naar ops/errors.go?

2023-11-07 09:55 UTC, Swopper050 commented on ops/multidir_broadcast.go
> +		return nil, ErrTypeAssert("tensor.Tensor", t.Clone())
will this break? Because if the type assertion fails, t will be `nil` right? So then this might panic

2023-11-07 09:56 UTC, Swopper050 commented on ops/opset13/abs.go
> +	MaxAbsInput = 1
We don't have comments for all these yet. Do we really want these comments? They seem trivial to me.

2023-11-07 09:57 UTC, Swopper050 commented on ops/opset13/add.go
> +)
When the number of `min` and `max` inputs is the same, I think it is better to just define `NAddInputs = 2`. And then return this variable for both `GetMinInputs()` and `GetMaxInputs()`

2023-11-07 09:59 UTC, Swopper050 commented on ops/opset13/add.go
> +)
Should be checked for all operators.

2023-11-07 10:07 UTC, Swopper050 commented on ops/opset13/div_test.go
> +			ops.ErrInvalidInputCount(1.0, &Div{}),
Should be a int 1

2023-11-07 10:09 UTC, Swopper050 commented on ops/opset13/gather_test.go
> +	assert.EqualError(t, err, "operator gather operator attribute error: invalid count 2 expected 1")
Modify `String()` method of gather operator to exclude `operator`

2023-11-07 10:17 UTC, Swopper050 commented on ops/opset13/squeeze.go
> +		return nil, nil
I think we want this to return an error?

2023-11-07 10:18 UTC, Swopper050 commented on ops/opset13/transpose.go
> +const TransposeInputs = 1
`NTransposeInputs`, or at least consistent with the rest.

2023-11-07 10:19 UTC, Swopper050 commented on ops/utils.go
> +
Errors maybe also move to `errors.go`?

2023-11-07 10:21 UTC, Swopper050 requested changes
See open comments

2023-11-07 12:52 UTC, wipsel commented on Makefile
> +GO1.19=ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.21
should be reverted?

2023-11-08 13:43 UTC, Swopper050 approved these changes

2023-11-08 13:44 UTC, merged