Draft: Add LinearRegressor operator
AdvancedClimateSystems/gonnx pull request #184
Opened 2023-12-07 15:46 UTC by Swopper050

Closes #182

2023-12-13 08:10 UTC, wipsel requested changes

2023-12-13 08:10 UTC, wipsel commented on ops/opset13/linear_regressor.go
> +type PostTransformOption string
Docstring ?

2023-12-14 12:03 UTC, wipsel approved these changes

2023-12-14 12:09 UTC, wipsel commented on ops/opset13/linear_regressor.go
> +	NoTransform          PostTransformOption = "NONE"
Do these need to be exported ?

2023-12-14 12:09 UTC, wipsel submitted a review, later dismissed

2023-12-14 13:42 UTC, Swopper050 commented on ops/opset13/linear_regressor.go
> +	NoTransform          PostTransformOption = "NONE"
No

2023-12-14 14:07 UTC, merged